### ISSUE TITLE
How can we implement the progress bar for ngUpload?

### ISSUE THREAD

**Issue by ankurshah32** [twilson63/ngUpload#122]
Thanks. Its works well. I need to implement progessbar on top of this.
Can you please provide me a example?

**Comment by demisx** [comment]
+1

**Comment by twilson63** [comment]
Here is an example I did using the upload button directive which uses XHR2
-

https://github.com/twilson63/async-throwdown-nodejs

I would not use this for big files, the main use case I have had success
with is the quick upload of profile pictures and avatars.

Thanks

Tom


On Mon, Feb 16, 2015 at 4:16 PM, Dmitri Moore <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twilson63/ngUpload/issues/122#issuecomment-74573659>.
>



-- 
Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
<http://www.jackhq.com/calendar>

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.
